apiVersion: 1

datasources:
  - name: grafana-postgresql-datasource
    type: postgres
    access: proxy
    uid: 'road_vision_postgres'
    url: postgres_db:5432
    database: test_db
    user: user
    secureJsonData:
      password: pass
    jsonData:
      sslmode: disable
      database: test_db
      postgresVersion: 1600
    isDefault: true
    editable: true
