services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    command: mosquitto -c /mosquitto-no-auth.conf

  agent:
    build: .
    depends_on:
      - mqtt
    environment:
      MQTT_BROKER_HOST: "mqtt"